### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by hadifarnoud** [voidlabs/htmml#1]
I wanted to edit versafix theme to add RTL support and Tahoma theme. unfortunately though, I found no documentation for htmml templating language. I didn't figure out how to do it.

can you guys please write a documentation for htmml?

**Comment by bago** [comment]
htmml itself is documented in the main readme:
https://github.com/voidlabs/htmml/blob/master/README.md

Maybe you are looking for a "mosaico template language" documentation? This is "unrelated" to HTMML, and you may find something here: https://github.com/voidlabs/mosaico/wiki/Template-language
